fix: update arrow dependencies to v56.2 for lancedb compatibility
When building, I was getting the following error:
| error[E0308]: mismatched types
|    --> src/database/vectors.rs:201:17
|     |
| 201 |                 arrow::datatypes::DataType::FixedSizeList(_, size) => {
|     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `lancedb::arrow::arrow_schema::DataType`, found `arrow::datatypes::DataType`
|     |
| note: two different versions of crate `arrow_schema` are being used;
| two types coming from two different versions of the same crate are
| different types even if they look the same

Update arrow, arrow-array, and arrow-schema from v55.2 to v56.2 to resolve
version conflicts with lancedb v0.22.

Signed-off-by: Justin Stitt <justinstitt@google.com>